# based on swissarmy - not enough reason to build a separate image frequently for a rarely used utility image
FROM mbentley/swissarmy:latest

USER nobody
CMD echo "Available commands:"; apk -q info -L bind-tools | awk -F '/' '{print "  " $NF}'
